<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.8AcIoQT' shared service.

return $this->privates['.service_locator.8AcIoQT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'userManager' => array('services', 'fos_user.user_manager', 'getFosUser_UserManagerService.php', true),
));
