<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Controller\Api\ApiAuthController' shared autowired service.

$this->services['App\Controller\Api\ApiAuthController'] = $instance = new \App\Controller\Api\ApiAuthController();

$instance->setContainer(($this->privates['.service_locator.KTVqfp6'] ?? $this->load('get_ServiceLocator_KTVqfp6Service.php'))->withContext('App\\Controller\\Api\\ApiAuthController', $this));

return $instance;
