<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Controller\Api\ApiUserController' shared autowired service.

$this->services['App\\Controller\\Api\\ApiUserController'] = $instance = new \App\Controller\Api\ApiUserController();

$instance->setContainer(($this->privates['.service_locator.KTVqfp6'] ?? $this->load('get_ServiceLocator_KTVqfp6Service.php'))->withContext('App\\Controller\\Api\\ApiUserController', $this));

return $instance;
