<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'nelmio_api_doc.describers.config' shared service.

return $this->privates['nelmio_api_doc.describers.config'] = new \Nelmio\ApiDocBundle\Describer\ExternalDocDescriber(['info' => ['title' => 'Symfony JWT API', 'description' => 'Symfony JWT API docs', 'version' => '1.0.0'], 'securityDefinitions' => ['Bearer' => ['type' => 'apiKey', 'description' => 'Authorization: Bearer {jwt}', 'name' => 'Authorization', 'in' => 'header']], 'security' => [0 => ['Bearer' => []]]]);
