<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCv8Ojmx\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCv8Ojmx/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCv8Ojmx.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCv8Ojmx\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerCv8Ojmx\srcApp_KernelDevDebugContainer(array(
    'container.build_hash' => 'Cv8Ojmx',
    'container.build_id' => 'a394c8c9',
    'container.build_time' => 1591740389,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerCv8Ojmx');
