<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOD704tl\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOD704tl/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOD704tl.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOD704tl\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerOD704tl\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'OD704tl',
    'container.build_id' => '5a4203e7',
    'container.build_time' => 1591743402,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOD704tl');
